/**
 * PocketLlama — TypeScript type definitions.
 * Central types for connections, chats, messages, and Ollama models.
 */

/** A saved connection to an Ollama instance via the PocketLlama proxy. */
export interface Connection {
  id: string;
  url: string;
  key: string;
  name: string;
  createdAt: number;
  lastUsed: number;
}

/** A single chat conversation. */
export interface Chat {
  id: string;
  connectionId: string;
  model: string;
  title: string;
  createdAt: number;
  updatedAt: number;
}

/** A single message within a chat. */
export interface Message {
  id: string;
  chatId: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  /** Model's internal reasoning from <think> tags (thinking/reasoning models). */
  thinking?: string;
  /** Base64-encoded images attached to this message (for vision models). */
  images?: string[];
  /** ID of the message this one follows (null for the first message in a chat). */
  parentId: string | null;
  /**
   * Branch index among siblings sharing the same parentId.
   * Used for tree navigation (e.g. "1/2", "2/2" like ChatGPT).
   */
  branchIndex: number;
  createdAt: number;
}

/** An Ollama model as returned by /api/tags. */
export interface OllamaModel {
  name: string;
  size: number;
  modifiedAt: string;
  digest: string;
  details?: {
    format?: string;
    family?: string;
    parameterSize?: string;
    quantizationLevel?: string;
  };
}

/** Data encoded in the QR code generated by the PocketLlama server script. */
export interface QRPayload {
  url: string;
  key: string;
}

/** Possible connection states for the UI. */
export type ConnectionStatus = 'disconnected' | 'connecting' | 'connected' | 'error';

/** Ollama /api/chat message format (sent to the API). */
export interface OllamaChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  images?: string[];
}
